# This is a basic workflow to help you get started with Actions

name: Terraform

# Controls when the workflow will run
on:
  workflow_dispatch:
  
env:
  TF_WORKSPACE: "${{ secrets.TF_WORKSPACE }}"
  TF_CLOUD_ORGANIZATION: "${{ secrets.TF_CLOUD_ORGANIZATION }}"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  AWS_REGION: "${{ secrets.AWS_REGION }}"
  CONFIG_DIRECTORY: "."
  
jobs:
  terraform_destroy:
    if: github.repository != 'PruebasPersonales'
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions: # granular permissions
      # so GitHub can check out this repo using the default github.token
      contents: read
    defaults:
      run:
        working-directory: ${{ env.CONFIG_DIRECTORY }}
    
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3.5.2
      
    # Configure HCP Terraform API token, since we are using remote backend option of HCP Terraform in AWS code
    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.2
      with:
        cli_config_credentials_token: ${{ env.TF_API_TOKEN }}
    
    # Invoke the Terraform commands
    - name: Terraform init and validate
      run: |
        echo `pwd`
        echo "** Running Terraform Init**"
        terraform init
        
        echo "** Running Terraform Validate**"
        terraform validate
      working-directory: ${{ env.CONFIG_DIRECTORY }}
