# This is a basic workflow to help you get started with Actions

name: Terraform

# Controls when the workflow will run
on:
  workflow_dispatch:
  
env:
  TF_WORKSPACE: "${{ secrets.TF_WORKSPACE }}"
  TF_CLOUD_ORGANIZATION: "${{ secrets.TF_CLOUD_ORGANIZATION }}"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  AWS_REGION: "${{ secrets.AWS_REGION }}"
  CONFIG_DIRECTORY: "."
  
jobs:
  terraform_destroy:
    if: github.repository != 'PruebasPersonales'
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions: # granular permissions
      # so GitHub can check out this repo using the default github.token
      contents: read
    defaults:
      run:
        working-directory: ${{ env.CONFIG_DIRECTORY }}
    
    steps:
    - name: "Checkout"
      uses: actions/checkout@master
      
    - name: "Terraform Init"
      uses: hashicorp/terraform-github-actions@master
      with:
       tf_actions_version: 0.12.13
       tf_actions_subcommand: "init"
       