# This is a basic workflow to help you get started with Actions

name: Terraform

# Controls when the workflow will run
on:
  workflow_dispatch:
  
env:
  TF_WORKSPACE: "${{ secrets.TF_WORKSPACE }}"
  TF_CLOUD_ORGANIZATION: "${{ secrets.TF_CLOUD_ORGANIZATION }}"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  AWS_REGION: "${{ secrets.AWS_REGION }}"
  CONFIG_DIRECTORY: "."
  
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Configure Terraform Cloud Backend
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: |
          terraform init \
            -backend-config="hostname=app.terraform.io" \
            -backend-config="organization=${{ secrets.TF_CLOUD_ORGANIZATION }}" \
            -backend-config="workspaces.name=${{ secrets.TF_WORKSPACE }}"

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
